version: "3.4"
services:
  lin:
    image: ubuntu
    networks:
      my_network:
        ipv4_address: 172.28.0.4
        aliases:
          - my_alias_a
    entrypoint:
      - 'bash'
      - '-c'
      - |
        apt-get update &&
        apt-get install -y wget &&
        apt-get install -y iputils-ping &&
        apt -y install zsh &&
        apt -y install git &&
        sh -c "$(wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)" &&
        tail -f /dev/null
  app-1:
    image: app
    networks:
      my_network:
        ipv4_address: 172.28.0.3
        aliases:
          - my_alias_b
    entrypoint:
      - 'bash'
      - '-c'
      - |
        python3 run.py
  app-2:
    image: app
    ports:
      - "8000:8000"
    networks:
      my_network:
        ipv4_address: 172.28.0.2
        aliases:
          - my_alias_c
    entrypoint:
      - 'bash'
      - '-c'
      - |
        cd src/api  && uvicorn api:app --host 0.0.0.0 --reload

networks:
  my_network:
    ipam:
      config:
        - subnet: 172.28.0.0/16
