# Countries

COUNTRIES = {
    'Belgium': 'BELGIUM_BE',
    'Greece': 'GREECE_GR',
    'Lithuania': 'LITHUANIA_LT',
    'Portugal': 'PORTUGAL_PT',
    'Bulgaria': 'BULGARIA_BG',
    'Spain': 'SPAIN_ES',
    'Luxembourg': 'LUXEMBOURG_LU',
    'Romania': 'ROMANIA_RO',
    'Czechia': 'CZECH_REPUBLIC_CZ',
    'France': 'FRANCE_FR',
    'Hungary': 'HUNGARY_HU',
    'Slovenia': 'SLOVENIA_SI',
    'Denmark': 'DENMARK_DK',
    'Croatia': 'CROATIA_HR',
    'Malta': 'MALTA_MT',
    'Slovakia': 'SLOVAKIA_SK',
    'Germany': 'GERMANY_DE',
    'Italy': 'ITALY_IT',
    'Netherlands': 'NETHERLANDS_NL',
    'Finland': 'FINLAND_FI',
    'Estonia': 'ESTONIA_EE',
    'Cyprus': 'CYPRUS_CY',
    'Austria': 'AUSTRIA_AT',
    'Sweden': 'SWEDEN_SE',
    'Ireland': 'IRELAND_IE',
    'Latvia': 'LATVIA_LV',
    'Poland': 'POLAND_PL',
}
