{
 "title": "API Stress Testing",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Cross Worker Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Time spent from Request to Monthly data Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg(final_delay_nanos{job=\"monthly-worker\"} - on(country, date) final_delay_nanos{job=\"data-worker\"}) #  by (country)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time spent from Request to each Worker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg(final_delay_nanos{job=\"monthly-worker\"} - on(country, date) final_delay_nanos{job=\"data-worker\"})",
     "legendFormat": "monthly worker delay"
    },
    {
     "expr": "avg(final_delay_nanos{job=\"daily-worker\"} - on(country, date) final_delay_nanos{job=\"data-worker\"})",
     "legendFormat": "daily worker delay"
    },
    {
     "expr": "avg(final_delay_nanos{job=\"weekly-worker\"} - on(country, date) final_delay_nanos{job=\"data-worker\"})",
     "legendFormat": "weekly worker delay"
    }
   ]
  },
  { "title": "Data Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "[Data Worker]: Time for a 30Day request",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "data_time_per_request_bucket{job=~\"data-worker-*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[Data Worker]: Time to save in DB",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "data_time_insert_db_bucket{job=~\"data-worker-*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[Data Worker]: Total Requests Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(data_total_requests_processed_total{job=\"data-worker\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[Data Worker]: Total Bytes Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(data_total_bytes_received_total{job=\"data-worker\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Daily Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "[Daily Worker]: Total Requests Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(daily_total_requests_processed_total{job=\"daily-worker\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[Daily Worker]: Total Bytes Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(daily_total_bytes_received_total{job=\"daily-worker\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[Daily Worker]: Total Bytes After Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(daily_total_bytes_after_process_total{job=\"daily-worker\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[Daily Worker]: Time to parse data",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "daily_time_parse_bucket{job=\"daily-worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[Daily Worker]: Time to write data to DB",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "daily_time_insert_db_bucket{job=\"daily-worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[Daily Worker]: Time to consume and forward data",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "daily_time_forward_bucket{job=\"daily-worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Weekly Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "[Weekly Worker]: Total Requests Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "sum(rate(weekly_total_requests_processed_total{job=\"weekly-worker\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[Weekly Worker]: Total Bytes Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(weekly_total_bytes_received_total{job=\"weekly-worker\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[Weekly Worker]: Total Bytes After Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(weekly_total_bytes_after_process_total{job=\"weekly-worker\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[Weekly Worker]: Time to parse data",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "weekly_time_parse_bucket{job=\"weekly-worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[Weekly Worker]: Time to write data to DB",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "weekly_time_insert_db_bucket{job=\"weekly-worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[Weekly Worker]: Time to consume and forward data",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "weekly_time_forward_bucket{job=\"weekly-worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Monthly Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "[Monthly Worker]: Total Requests Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "sum(rate(monthly_total_requests_processed_total{job=\"monthly-worker\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[Monthly Worker]: Total Bytes Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(monthly_total_bytes_received_total{job=\"monthly-worker\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[Monthly Worker]: Total Bytes After Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(monthly_total_bytes_after_process_total{job=\"monthly-worker\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[Monthly Worker]: Time to parse data",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "monthly_time_parse_bucket{job=\"monthly-worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[Monthly Worker]: Time to write data to DB",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "targets": [
    {
     "expr": "monthly_time_insert_db_bucket{job=\"monthly-worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[Monthly Worker]: Time to consume and forward data",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 105 },
   "targets": [
    {
     "expr": "monthly_time_forward_bucket{job=\"monthly-worker\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}