---
version: '3.7'
services:
    db:
        image: postgres:15.2-alpine
        restart: always
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_DB: metabase
            POSTGRES_USER: metabase
            POSTGRES_PASSWORD: db_password
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            - my_network

volumes:
    db_data:
networks:
    my_network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.28.0.0/16
