---
version: '3.7'
services:
    linux-machine-for-testing:
        image: ubuntu
        container_name: linux-machine-for-testing
        networks:
            - my_network
        #ipv4_address: 172.28.0.4
        #aliases:
        #  - my_alias_a
        entrypoint:
            - bash
            - -c
            - |
              apt-get update &&
              apt-get install -y wget &&
              apt-get install -y iputils-ping &&
              apt -y install zsh &&
              apt -y install git &&
              sh -c "$(wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)" &&
              apt-get install curl -y &&
              apt-get install unzip -y &&
              curl -LO https://github.com/redpanda-data/redpanda/releases/latest/download/rpk-linux-amd64.zip &&
              mkdir -p ~/.local/bin &&
              unzip rpk-linux-amd64.zip -d ~/rpk &&
              apt-get install -y postgresql-client &&
              tail -f /dev/null

    prometheus:
        image: prom/prometheus:latest
        ports:
            - 9090:9090
        volumes:
            - ../prometheus.yml:/etc/prometheus/prometheus.yml
        networks:
            - my_network


networks:
    my_network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.28.0.0/16
